selectionsort: selectionsort.cpp SpandexArray.o
	g++ -o selectionsort selectionsort.cpp SpandexArray.o

SpandexArray.o: SpandexArray.h SpandexArray.cpp
	g++ -c -g SpandexArray.cpp
clean:
	rm selectionsort
