insertionsort: insertionsort.cpp SpandexArray.o
	g++ -o insertionsort insertionsort.cpp SpandexArray.o

SpandexArray.o: SpandexArray.h SpandexArray.cpp
	g++ -c -g SpandexArray.cpp
clean:
	rm insertionsort
